---
title: "p8105_hw5_ps3194"
author: "Pangsibo Shen"
date: "11/10/2020"
output: html_document
---


```{r}
library(tidyverse)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
set.seed(123)
```

## Problem 1

Read in the table

```{r}
homicide_df =
  read_csv("./data/homicide-data.csv") %>%
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved",
    )
  ) %>%
  select(city_state, resolved) %>%
  filter(city_state != "Tulsa_AL")
```
Raw data has 52179 observations and 12 variables including: uid,reported_date, victim_last, victim_first, victim_race,victim_age, victim_sex, city, state, lat, lon and disposition. 

```{r}
aggregate_df =
  homicide_df %>%
  group_by(city_state) %>%
  summarise(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )

aggregate_df
```
Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>%
  broom:: tidy()
```

Try to iterate...

```{r}
results_df = 
  aggregate_df %>%
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state,estimate)) %>%
  ggplot(aes(x = city_state, y =estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle =90, vjust = 0.5, hjust = 1))
```

## Problem 2
load data
```{r message= FALSE}
data_1 = read_csv("data/lda_data/con_01.csv")
```
tidy data
```{r message= FALSE}
path_df = 
  tibble(
    path = list.files("data/lda_data")
  ) %>%
  mutate(
    path = str_c("data/lda_data/", path),
    data = map(.x = path, ~ read_csv(.x) )
         ) %>%
  unnest(data) %>%
  separate(path,c("arm","subject_id"),-6) %>%
  mutate(
    arm = case_when(
      arm == "data/lda_data/con_" ~ "control",
      arm == "data/lda_data/exp_" ~ "experimental"
    )
  )

path_df$subject_id = str_replace(path_df$subject_id, ".csv","")

path_df = 
  path_df %>%
  pivot_longer(
   cols = starts_with("week"),
   names_to = "week",
   names_prefix = "week_",
   values_to = "observation",
  ) %>%
  transform(
    subject_id = as_factor(as.numeric(subject_id)),
    arm = as_factor(arm),
    week = as.numeric(week)
            )
```

plot
```{r}
path_df %>%
  ggplot(aes(x = week, y = observation, gourp = subject_id, color = arm)) +
  geom_line() +
  scale_x_continuous(breaks= c(1,2,3,4,5,6,7,8)) +
  ggtitle("spaghetti plot showing observations on each subject over time")
```
## Problem 3

```{r}
#The probability that a false null hypothesis is rejected is referred to as power
sim_t_test = function(mu , samp_size = 30, sigma = 5) {
  
  sim_data = 
    tibble(
      broom::tidy(t.test(rnorm(n = samp_size, mean = mu, sd = sigma)))
    ) %>%
    select(c(estimate, p.value))
  sim_data
}
```


## Let's simulate 5000 times


```{r}
output_0 = vector("list", length = 5000)

for (i in 1:5000) {
  
  output_0[[i]] = sim_t_test(0)
  
}

bind_rows(output_0)

power = (bind_rows(output_0) %>%
  filter(
    p.value > 0.05 
  ) %>% nrow())/5000
```

## simulate other mu values


```{r}
# mu_list = 
#   list(
#     "mu = 1" = 1,
#     "mu = 2" = 2,
#     "mu = 3" = 3,
#     "mu = 4" = 4,
#     "mu = 5" = 5,
#     "mu = 6" = 6
#   )
# 
# output = vector("list", length = 6)
# 
# 
# for (i in 1:6) {
#   
#   output[[i]] = 
#     rerun(5000, sim_t_test(mu = mu_list[[i]])) %>% 
#     bind_rows()
#   
# }
```

```{r}

# output_power = vector("list", length = 6)
# 
# for (i in 1:6) {
# 
# output_power[[i]] =  
#   output[[i]] %>%
#   filter(
#     p.value > 0.05 
#   ) %>% nrow()
#   
# }

```

```{r}
sim_results = 
  tibble(
    mu = c(0,1,2,3,4,5,6)
  ) %>% 
  mutate(
    output_lists = map(.x = mu, ~ rerun(5000, sim_t_test(.x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)
```

```{r}
sim_results_plot_1 =
  sim_results %>%
  filter(p.value < 0.05) %>%
  group_by(mu) %>%
  summarise(power = n()/5000) %>%
  transform(mu = as.factor(mu)) %>%
  ggplot(aes(mu, power)) +
  geom_bar(stat='identity') +
  ylab("the power of the test" ) +
  xlab("true value of mu")

sim_results_plot_1

sim_results_plot_2 =
  sim_results %>%
  group_by(mu) %>%
  summarise(avg_estimate = mean(estimate))  %>%
  transform(mu = as.factor(mu))
  #ggplot(aes(mu, avg_estimate)) +
  #geom_point(stat='identity') +
  #ylab("average estimate of mu hat" ) +
  #xlab("true value of mu")

sim_results_plot_3 =
  sim_results %>%
  filter(p.value < 0.05) %>%
  group_by(mu) %>%
  summarise(avg_estimate = mean(estimate)) %>%
  transform(mu = as.factor(mu))

  #ggplot(aes(mu, avg_estimate)) +
  #geom_point(stat='identity') +
  #ylab("average estimate of mu hat" ) +
  #xlab("true value of mu")

ggplot() +
  geom_point(data = sim_results_plot_2, aes(mu, avg_estimate, color = "all mu hat")) +
  geom_point(data = sim_results_plot_3, aes(mu, avg_estimate, color = "mu hat null rejected")) +
  ylab("average estimate of mu hat" ) +
  xlab("true value of mu")
```


